### ISSUE TITLE
different behavior on cljs vs clj for datomic uris

### ISSUE THREAD

**Issue by dustingetz** [lambdaisland/uri#3]
```
$ boot -d lambdaisland/uri:1.1.0 repl
boot.user=> (require '[lambdaisland.uri :refer [uri join]])
boot.user=> (uri "datomic:free://datomic:4334/asdf")
#lambdaisland/uri "datomic:free://datomic:4334/asdf"

$ planck --classpath=`boot -d lambdaisland/uri:1.1.0 show -c`
cljs.user=> (require '[lambdaisland.uri :refer [uri join]])
cljs.user=> (uri "datomic:free://datomic:4334/root")
#lambdaisland.uri.URI{:scheme "datomic", :user nil, :password nil, :host nil, :port nil, :path "free://datomic:4334/root", :query nil, :fragment nil}
```

goog.Uri has the same problem. java.net.uri works. Perhaps Datomic is violating the uri spec?

**Comment by plexus** [comment]
The problem is that how to interpret a url depends on the "scheme", (ie.
the protocol, the part before the :). For http/https/mailto/ftp/data etc
there's a standard (an RFC) how to interpret the rest of the uri. For
datomic: there is no spec (RFC).

Lambdaisland/uri is meant to work with http/https/ftp, or other schemes
that follow the same structure. This does not include datomic
unfortunately.

**Comment by plexus** [comment]
As a side note, I don't think there's a difference in parsing here, the
resulting URI object is just printed differently. Seems the custom printer
doesn't work with Planck.

You can try this in clojure to see how it's been parsed : (into {} (uri
"datomic:..."))

Because the : is not followed by // the rest of the uri is interpreted as a
relative path, which is per the http uri RFC.

**Comment by dustingetz** [comment]
Ok, thanks.

**Comment by dustingetz** [comment]
Is this new uri type something I might be able to teach the library about?

**Comment by plexus** [comment]
Not really, the parsing is done with a regex which is hard coded. You could
use the source as inspiration for your own version.

What exactly are you trying to do? What you could do is chop off the
datomic: part and parse the rest, at least that part seems to have a
similar structure as a http uri.

On Sep 29, 2017 18:25, "Dustin Getz" <notifications@github.com> wrote:

Is this new uri type something I might be able to teach the library about?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/lambdaisland/uri/issues/3#issuecomment-333172973>, or mute
the thread
