### ISSUE TITLE
data.json dependency necessary?

### ISSUE THREAD

**Issue by isker** [lambdaisland/uri#8]
Hi!  I just quickly skimmed so may be dead wrong here, but it's not clear what the data.json dep is for.  Looks like it was added in this commit https://github.com/lambdaisland/uri/commit/2f4c756baf436c3048ab47847dfff4d6e61ca6fc, which doesn't seem to use it.

Thanks!

**Comment by plexus** [comment]
No, it's not necessary. It was intended to be used to read in test data and so should have been a test-time dependency in any case.

It seems it's been removed on master for some time now, but I never put out a release because I was hoping to finish `normalize` before the next release. I'll have a look if I can wrap that up, or if I can do a new release without `normalize`.

**Comment by plexus** [comment]
This has been dropped for some time, `lambdaisland/uri` only depends on Clojure itself.
